### ISSUE TITLE
Problem with projection and geoJSON?

### ISSUE THREAD

**Issue by gbazin-eso** [d3/d3-geo-projection#116]
Hi,

I have an issue with the representation of a geoJSON file.  It seems that the contours are, in some cases (depending on the rotation), misinterpreted and inner/outer regions are mixed up.  See the attached screenshots and the codepen https://codepen.io/anon/pen/wdYmqL where you can manually rotate the projection.

Do you think it is an intrinsic problem of geoJSON, a projection-related problem, or a anything wrong in my example?  Thanks!

![mw_nopb](https://cloud.githubusercontent.com/assets/28803785/26241771/324c94b4-3c86-11e7-9ac1-ace870cec0e0.png)
![mw_pb](https://cloud.githubusercontent.com/assets/28803785/26241778/38d22cfe-3c86-11e7-95c4-a96b2334ba2a.png)

**Comment by mbostock** [comment]
Hmm. Well, partly this is expected when you have an orthographic projection where the clip angle is not 90° so the back hemisphere is visible:

![untitled 6](https://cloud.githubusercontent.com/assets/230541/26250786/0902eed0-3c60-11e7-8f59-f53fe11f7201.png)

If you want to display the whole earth, I think you want to set the clip angle to 180° rather than using antimeridian clipping, if you aren’t already, since you won’t want a cut along the antimeridian.

```js
var projection = d3.geoOrthographic()
    .scale(radius)
    .clipAngle(180);
```

That seems to fix some of the transient winding order issues, but, it looks like there are other winding order issues, probably because the topology is more interesting with the milky way shape than typical continents.

![untitled 7](https://cloud.githubusercontent.com/assets/230541/26250898/638dcaa0-3c60-11e7-92ba-4ce87b672807.png)

See the [winding order bl.ock](https://bl.ocks.org/mbostock/a7bdfeb041e850799a8d3dce4d8c50c8) for details. You probably need to reverse one (or more) of the rings in the GeoJSON to fix the winding order problem, but I think you’ll have to figure that out by hand. I might look later if I have time.

**Comment by mbostock** [comment]
Here’s a fixed-ish version:

https://bl.ocks.org/mbostock/15a373ce034cbc4ad604767c0eac05cb

![image](https://cloud.githubusercontent.com/assets/230541/26254568/daded33c-3c6b-11e7-8f53-614f2135e844.png)

**Comment by gbazin-eso** [comment]
Hi,

Indeed.  Thank you very much for your help!

Regards,
G.

**Comment by gbazin-eso** [comment]
Hi Mike,

Sorry to re-open that.  In your example, you use a canvas and it seems that it is not so convenient to use with d3.js.  In particular, we want to manipulate many svg elements on top of the milky way.  Would you have a solution which works without the canvas?
Thanks ;)

Best regards,
G.

P.S.  BTW, d3-celestial https://github.com/ofrohn/d3-celestial (e.g. http://armchairastronautics.blogspot.de/p/skymap.html) shows the same problem with the milky way in orthographic projection.

**Comment by mbostock** [comment]
Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
