### ISSUE TITLE
using d3-geo-projection

### ISSUE THREAD

**Issue by DDDgfx** [d3/d3-geo-projection#128]
Can anyone advise on how to import d3-geo-projection with d3s default bundle with es6 imports?  I have tried:

```js
import * as d3 from 'd3';
import 'd3-geo-projection';
```

```js
import * as d3 from 'd3';
import {geoAitoff} from 'd3-geo-projection';
```

neither results in being able to call `var proj = d3.geoAitoff()`;

Is the solution to do a custom rollup that includes d3-geo-projection? I have not figured out how to do that yet.  Hope you can help.

**Comment by DDDgfx** [comment]
Should I just open the index.js within d3 and add:

export * from "d3-geo-projection";

??

**Comment by mbostock** [comment]
Generally speaking if you are consuming ES modules, you should be using the modules individually, as in d3-geo rather than d3. In that case you could say:

```js
import * as d3Geo from "d3-geo";
import * as d3GeoProjection from "d3-geo-projection";
```

But, it would be cleaner to just import the things you are using, as in:

```js
import {geoPath} from "d3-geo";
import {geoAitoff} from "d3-geo-projection";
```

You’re welcome to roll your own bundle by forking the [default d3 bundle](https://github.com/d3/d3) and adding d3-geo-projection, too. 

If you have further questions, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by DDDgfx** [comment]
Thanks Mike - It blows my mind that you get to this stuff.

**Comment by DDDgfx** [comment]
Just to clarify... If I import d3-geo-projections via:
import * as d3GeoProjection from "d3-geo-projection";
Would I then access the projections . with 
var proj = d3GeoProjection.geoAitoff(); // Im not really using Aitoff..
rather than
var proj = d3.geoAitoff;

Likewise if I import via:

import {geoAitoff} from "d3-geo-projection";
will I use 
var proj = geoAitoff(); 
rather than 
var proj = d3.geoAitoff();

**Comment by mbostock** [comment]
Yes.

There’s no way to merge ES imports into a shared object, so if you use `import *`, you have to use separate names for each module. Given that all the D3 modules have unique names, you’ll get much shorter code if you import the symbols individually rather than using `import *`.

**Comment by DDDgfx** [comment]
Ah so if I do it as us suggest:
    import {geoPath} from "d3-geo";
    import {geoAitoff} from "d3-geo-projection";

I can use my convetional way of calling:

var path = d3.geoPath()....

and

var proj = de.goAitoff();

I'll try

**Comment by mbostock** [comment]
No, this:

```js
import {geoPath} from "d3-geo";
import {geoAitoff} from "d3-geo-projection";

var path = geoPath();

var projection = geoAitoff();
```
