### ISSUE TITLE
polyhedron.waterman projection clearly differs from waterman’s version

### ISSUE THREAD

**Issue by jrus** [d3/d3-geo-projection#22]
This version seems to just be a Gnomonic projection on particular sections, while Waterman’s own projection is something different. (I can’t actually figure out what the technical details are on Waterman’s version.) The easiest place to see the difference is in the shape of the parallels near the poles. On a globe or azimuthal projection centered on a pole, these are shaped like quarter circles. In the d3/Gnomonic version, they are stretched toward the center. By contrast, in Waterman’s projection, the middle of each quarter circle is squished toward poles.

I highly recommend adding an explicit disclaimer that this is not actually Waterman’s projection per se. Ideally it would be possible to ask Waterman for the details and implement the projection properly. Even if the projection is going to stay as is though, users should be warned in the documentation about exactly what they’re getting.

**Comment by jasondavies** [comment]
(Firstly, d3-geo-projection doesn’t have the Waterman “projection”, so this isn’t the right place for this issue.)

I’ve asked Waterman about the technical details, but he seems to think that his [method P](http://www.watermanpolyhedron.com/methodp.html) is only marginally better than using gnomonic, and since the gnomonic is more widely supported, he used it in [his world maps of 2012](http://www.watermanpolyhedron.com/worldmap).

The way I see it, his projection is more about using a particular unfolding of the W5 polyhedron, so the face projection used is less important.

**Comment by jrus** [comment]
Personally I think both Waterman’s “method P” and the Gnomonic projection are quite bad for areas as large as an octant, with dramatic amounts of distortion, and in Waterman’s method additionally some weirdly kinked lines. A Gnomonic projection is only really suitable when you need to guarantee that great circles are mapped to straight lines, and otherwise is a poor tradeoff. Even on an icosahedron-based map it causes quite noticeable distortion near the corners.

But that’s all neither here nor there. The real issue IMO is clearly indicating in the code and in documentation (e.g. at http://bl.ocks.org/mbostock/4458497) that this projection is different from the one Waterman uses on his poster maps, since people are likely to otherwise not realize.
