### ISSUE TITLE
SyntaxError: Invalid character '\u8224'

### ISSUE THREAD

**Issue by DDDgfx** [d3/d3-geo-projection#23]
I am using d3 and d3.geo.projections to render a map of some simplified admin0 data. I am also using codekiy with uglify to compile my code. All goes well until I append d3.geo.projections.js. 

There after my map does not render and I get an error message of in my console:
SyntaxError: Invalid character '\u8224'
...which seems to refer to some special characters in country names. For example "Saint Barthï¿½lemy"

However, I am not using any of the extended projections yet, I get the error just from including the script. Uninclude the extended projections and the error goes away. Can you offer any thoughts?

**Comment by mbostock** [comment]
In past versions you needed to ensure that it was loaded with the UTF-8 charset. That means one of these must be true:

* The server must serve d3.geo.projection.js with the charset UTF-8 (alas does not apply to GitHub Pages and thus d3js.org).
* The page must have a `<meta charset="utf-8">` in the head before the script is loaded.
* The script element must have a `charset="utf-8"` attribute.

For example:

```html
<script src="d3.geo.projection.js" charset="utf-8"></script>
```

Since d3-geo-projection 1.0 (and D3 4.0), the code is written exclusively in ASCII so this is no longer a requirement.
