### ISSUE TITLE
fs.readFileSync is not a function

### ISSUE THREAD

**Issue by lapidus** [d3/d3-geo-projection#31]
I am trying the node approach (using webpack):
var d3 = require("d3");
require("d3-geo-projection")(d3);

But I get this error:
Uncaught TypeError: fs.readFileSync is not a function

Any ideas?

**Comment by mbostock** [comment]
You need to use Browserify’s [brfs transform](https://github.com/substack/brfs); you can’t just use Webpack to bundle d3-geo-projection directly from the source. (Alternatively, you need to require the built [d3.geo.projection.js](https://github.com/d3/d3-geo-projection/blob/master/d3.geo.projection.js) rather than the main entry defined in the package.json, which is intended for Node.)

The code in this repository will soon be restructured for D3 4.0 and replaced with ES6 modules, eliminating the use of fs.readFileSync.

**Comment by lapidus** [comment]
THANK YOU!

**Comment by joncursi** [comment]
Hey @mbostock - I'm running into the same fs.readFileSync error as the OP stated, however this package is [post 4.0 migration](https://github.com/d3/d3-geo-projection/issues/32) now. The following

```js
    import * as d3 from 'd3';
    require('d3-geo-projection')(d3);
    var projection = d3.geoKavrayskiy7();
```

Will error out:

```
Uncaught TypeError: fs.readFileSync is not a function
```

I'm not using Webpack or Browserify - is there another way to get this to load the proper dependencies via just `import` / `export` statements? Thanks!
