### ISSUE TITLE
D3 Geo doesn't work with browserify

### ISSUE THREAD

**Issue by Calvein** [d3/d3-geo-projection#5]

**Comment by admackin** [comment]
Since finding this bug, I've switched to using the recommended `require()` method from the README. However, since the `require("d3-geo-projection")(d3);` line is still in my page's source JS, which I run browserify over, browserify still chokes (even though it shouldn't, and I've just filed a [bug](https://github.com/substack/node-browserify/issues/1129) for this).

(Unless I'm missing something obvious about how to include d3-geo in an app which uses browserify)

However, as noted over at that bug report, there is a one-line change to `index.js` which would enable d3-geo-projection to work around browserify's brokenness:

If I replace the first two lines of `index.js` with 

    var fs = require("fs");
    var path = require("path");

`browserify` runs without complaint.
