### ISSUE TITLE
Tobler hyperelliptical projection?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-geo-projection#66]
https://en.wikipedia.org/wiki/Tobler_hyperelliptical_projection

**Comment by easadler** [comment]
I gave this a shot in order to learn how map projections works. My solution doesn't always line up with Tobler's examples in his paper. Here is a link to [block](https://bl.ocks.org/easadler/d66f761a9c6df4d8c6bf3de6a0fbbe41). 

I would love to hear if anyone else has better working code or can me help speed up numerical integration or knows why the example differs from Tobler's.

![projection](https://gist.githubusercontent.com/easadler/d66f761a9c6df4d8c6bf3de6a0fbbe41/raw/2ee515c8dc8e76ff09132af733c426e954886339/thumbnail.png)

**Comment by Fil** [comment]
I have researched this as much as I could, but I still can't reconcile everything with the litterature. Sorry for sharing only partial results. 

First, the family of Foucaut projections:
http://blockbuilder.org/Fil/4db96f1250ad6118290e24d62e67187d
Here my trigonometry is too weak to reconcile this computation with the d3's geoFoucaut formula. It looks about the same with alpha=-Pi/2 or something, but not _exactly_.

By the way, this family of projections seems more interesting with alpha = 0.5. In my notes I outline the references and name of the author (capitaine De Prépetit Foucaut). Unfortunately the reference article is not available online.

![capture d ecran 2017-03-16 22 15 25](https://cloud.githubusercontent.com/assets/7001/24018910/2a1b4d98-0a96-11e7-9042-72d0d426ee2e.png)

Second, the family of superelliptical projections based on Tobler's paper:
http://blockbuilder.org/Fil/97df1cde24d2cbf7cf97632c0eca8f31
In this case, I struggled to understand what gamma was. Finally I realised that it's computed directly from the integral, ahem… in most cases. So far so good.

However: in the case of Figure 7, Tobler gives Pi/2, and my numbers are totally different. Graphing with PI/2 gives a totally different (and ugly) projection. So, I don't know! Something is off.

And in the case of figure 9, Tobler's map seems much more curved than mine, so, again, I don't know.

![capture d ecran 2017-03-16 22 15 55](https://cloud.githubusercontent.com/assets/7001/24018920/31c3345c-0a96-11e7-8e66-a9f5f29b65bb.png)


Not like I need them to use them :-) But it's a fun exploration of “Pseudocylindrical Equivalent projections”. If someone happens to solve the issues I'd be delighted to understand what I failed to see. (Also, if we want to implement them properly, there's some work to do to compute the interpolation list in one swoop instead of doing 100 partial integrals.)

In all these cases the invert function would have to be solved by a numeric approximation (see #85).

**Comment by Fil** [comment]
@easadler amazing coincidence: I see your post just after pressing "send" on mine. Checking your block now.

**Comment by Fil** [comment]
@easadler The only difference between our maps is that you didn't multiply x and divide y by the ratio a11 = 0.8679. Otherwise, it's just a matter of rotations, stroke-width and graticule to have the same image.

See:
![capture d ecran 2017-03-16 22 40 33](https://cloud.githubusercontent.com/assets/7001/24019746/9740e452-0a99-11e7-992c-232aeae9ade1.png)

**Comment by Fil** [comment]
PS: one of the most interesting elements of the paper is the end where Tobler gives formulas for errors. Indicates they could be minimized by numerical methods,so as to obtain the "least deformed" projection in this family. In 1973 it would have been quite a feat to realize, but now it should be quite feasible.

**Comment by easadler** [comment]
@Fil What a coincidence! I really appreciate the help. I didn't see the part of his paper with the formulas for errors, so I will have to check it out. 

PS: Nice job recreating his style!

**Comment by Fil** [comment]
Some aspects are quite interesting.

Polar aspect with k=8 and a clipAngle(90):
![capture d ecran 2017-03-17 07 25 08](https://cloud.githubusercontent.com/assets/7001/24031606/c6c3d28a-0ae3-11e7-8d2d-cdd3b9af1080.png)
![capture d ecran 2017-03-17 07 25 58](https://cloud.githubusercontent.com/assets/7001/24031607/c6c7249e-0ae3-11e7-8fef-c7eeeea20c39.png)

Briesemeistery-Bertiny aspect
![capture d ecran 2017-03-17 07 30 09](https://cloud.githubusercontent.com/assets/7001/24031608/c6cafff6-0ae3-11e7-8ba3-d7050ba5ac51.png)

**Comment by Fil** [comment]
I have checked every resource I have found including Snyder's “Flattening the Earth”: everyone seems to be using the same formula as @easadler and myself, and getting the same image, so I guess we can call it.
Clean implementation with inverse and access to parameters _k_, _alpha_ and _affine_ in #133.

**Comment by jrus** [comment]
Did you try emailing Tobler? He was responsive a couple times I emailed him in the past.

**Comment by msdsoftware** [comment]
@jrus, Tobler passed away two months ago.

**Comment by jrus** [comment]
Oh wow. I totally missed that. RIP. :(
