### ISSUE TITLE
mercator projection missing

### ISSUE THREAD

**Issue by lewis500** [d3/d3-geo-projection#91]
The readme suggests that there is a mercator projection as geoMercator, but it's not in the library.

**Comment by mbostock** [comment]
The following projections are exported by [d3-geo](https://github.com/d3/d3-geo), and included in [d3](https://github.com/d3/d3), rather than exported by d3-geo-projection:

* [d3.geoAlbers](https://github.com/d3/d3-geo/blob/master/README.md#geoAlbers)
* [d3.geoAzimuthalEqualArea](https://github.com/d3/d3-geo/blob/master/README.md#geoAzimuthalEqualArea)
* [d3.geoAzimuthalEquidistant](https://github.com/d3/d3-geo/blob/master/README.md#geoAzimuthalEquidistant)
* [d3.geoConicConformal](https://github.com/d3/d3-geo/blob/master/README.md#geoConicConformal)
* [d3.geoConicEqualArea](https://github.com/d3/d3-geo/blob/master/README.md#geoConicEqualArea)
* [d3.geoConicEquidistant](https://github.com/d3/d3-geo/blob/master/README.md#geoConicEquidistant)
* [d3.geoEquirectangular](https://github.com/d3/d3-geo/blob/master/README.md#geoEquirectangular)
* [d3.geoGnomonic](https://github.com/d3/d3-geo/blob/master/README.md#geoGnomonic)
* [d3.geoMercator](https://github.com/d3/d3-geo/blob/master/README.md#geoMercator)
* [d3.geoOrthographic](https://github.com/d3/d3-geo/blob/master/README.md#geoOrthographic)
* [d3.geoStereographic](https://github.com/d3/d3-geo/blob/master/README.md#geoStereographic)
* [d3.geoTransverseMercator](https://github.com/d3/d3-geo/blob/master/README.md#geoTransverseMercator)

**Comment by mbostock** [comment]
These projections are included in the README for completeness. I am updating the README now to make this behavior more clear.
